spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        show_sql: true
        # 추가로 출력을 예쁘게
        format_sql: true
        use_sql_comments: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: 'alstjsdlr990321@gmail.com'
    password: 'xzjyunqhesqabahf'
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

# 커스텀 설정 (Spring 내부 설정 아님)
jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes

